server:
  port: 8080

spring:
  application:
    name: menu
  profiles:
    active: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

api:
  url:
    store: ${api.url.store:http://store:8080}
    order: ${api.url.order:http://order:8080}
    inventory: ${api.url.inventory:http://inventory:8080}
    gateway: ${api.url.gateway:http://gateway:8080}

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

server:
  port: 8080